x-veld:
  executable:
    about:
      description: "hard-coded conversion of apis ner models to custom json format."
      topic:
        - "ETL"
        - "data sanitization"
    input:
      type: "folder"
      format: "custom"
      content: "Named entity recognition gold data"
      path: /veld/input/
      description: "This input is hard-wired to the apis spacy-ner repo and not made for generic usage."
    output:
      type: "folder"
      format: "json"
      content: "Named entity recognition gold data"
      path: /veld/output/

services:
  veld:
    build: .
    volumes:
      - ./src/:/veld/executable/
    command: python /veld/executable/extract_and_clean.py

